# FedAvg
# BATCH_SIZE = 128
# HIDDEN_NEURONS = 128
# HIDDEN_NEURONS1 = 64
# FL_ROUND_COUNT = 120
# LEARNING_RATE = 0.01
# LOCAL_ITERATION_COUNT = 1
# N_CLIENTS = 5
# INPUT_NODES = 10
# OUTPUT_NODES = 1
# DROPOUT_RATE = 0.5
# THRESHOLD = 0.5


# HIDDEN_NEURONS = 32
FL_ROUND_COUNT = 150
# LEARNING_RATE = 0.0005
# LOCAL_ITERATION_COUNT = 5
N_CLIENTS = 3
# INPUT_NODES =7
# OUTPUT_NODES = 1
# DROPOUT_RATE = 0.1
THRESHOLD = 0.5
# PREDICTION_TIMESTEP_IADVANCE=1
CHEBYCHEV_K = 15 # 8

LABEL = "label"  # target label
# LABEL = "T (degC)"
# LABEL = "internet"  # target label
# TO_DROP_COL = ["rh (%)", "rho (g/m**3)", "wv (m/s)", "max. wv (m/s)", "wd (deg)", "p (mbar)"]  # Correlated columns to drop
# TO_DROP_COL = []
DATA_FOLDER = "data"
TO_DROP_COL = []
# TO_DROP_COL = ['all_..soft',
#  'sum_intr.s',
#  'temp1_.temp',
#  'temp2_.temp',
#  'temp1_degC',
#  'temp2_degC',
#  'dev252.0_.util',
#  'dev8.0_.util',
#  'dev8.5_.util',
#  'cpu12_.usr',
#  'temp4_.temp',
#  'temp4_degC',
#  'all_..usr',
#  'cpu8_.usr',
#  'cpu0_.usr',
#  'temp3_.temp',
#  'temp3_degC',
#  'cpu6_.usr',
#  'cpu10_.usr',
#  'cpu4_.usr',
#  'cpu20_.usr',
#  'cpu16_.usr',
#  'cpu14_.usr',
#  'cpu12_.iowait',
#  'ldavg.1',
#  'cpu2_.usr',
#  'cpu18_.usr',
#  'dev252.0_tps',
#  'dev8.0_tps',
#  'tps',
#  'dev8.5_tps',
#  'i116_intr.s',
#  'cpu8_.iowait',
#  'cswch.s',
#  'rtps',
#  'ldavg.5',
#  'cpu8_.sys',
#  'cpu12_.sys',
#  'cpu0_.iowait',
#  'cpu6_.sys',
#  'cpu10_.sys',
#  'cpu2_.sys',
#  'all_..sys',
#  'cpu22_.usr',
#  'dev252.0_rd_sec.s',
#  'pgpgin.s',
#  'bread.s',
#  'dev8.5_rd_sec.s',
#  'dev8.0_rd_sec.s',
#  'cpu20_.sys',
#  'dev252.0_avgqu.sz',
#  'dev8.0_avgqu.sz',
#  'dev8.5_avgqu.sz',
#  'cpu16_.sys',
#  'cpu2_.iowait',
#  'cpu14_.sys',
#  'cpu4_.iowait',
#  'fault.s',
#  'cpu22_.sys',
#  'cpu4_.sys',
#  'ldavg.15',
#  'bwrtn.s',
#  'dev8.0_wr_sec.s',
#  'dev8.5_wr_sec.s',
#  'cpu18_.sys',
#  'dev8.5_await',
#  'cpu17_.usr',
#  'dev8.0_await',
#  'dev252.0_wr_sec.s',
#  'pgpgout.s',
#  'cpu0_.sys',
#  'dev252.0_await',
#  'cpu15_.usr',
#  'cpu19_.sys',
#  'cpu19_.usr',
#  'cpu17_.sys',
#  'cpu21_.usr',
#  'cpu21_.sys',
#  'cpu15_.sys',
#  'dev252.0_avgrq.sz',
#  'wtps',
#  'cpu13_.usr',
#  'cpu23_.sys',
#  'dev8.0_avgrq.sz',
#  'cpu13_.sys',
#  'dev8.5_avgrq.sz',
#  'cpu3_.sys',
#  'cpu1_.sys',
#  'cpu3_.iowait',
#  'cpu5_.sys',
#  'cpu11_.sys',
#  'cpu23_.usr',
#  'eth0_rxmcst.s',
#  'cpu19_.iowait',
#  'cpu20_.iowait',
#  'cpu7_.sys',
#  'cpu15_.iowait',
#  'cpu1_.usr',
#  'campg.s',
#  'cpu3_.usr',
#  'all_..irq',
#  'cpu9_.idle',
#  'cpu23_.iowait',
#  'cpu9_.iowait',
#  'irec6.s',
#  'dev252.1_svctm',
#  'eth1_rxdrop.s',
#  'cpu13_.iowait',
#  'pgfree.s',
#  'cpu5_.usr',
#  'cpu11_.iowait',
#  'cpu17_.iowait',
#  'cpu9_.sys',
#  'i022_intr.s',
#  'dev8.5_svctm',
#  'eth0_rxpck.s',
#  'dev252.0_svctm',
#  'cpu11_.idle',
#  'i133_intr.s',
#  'dev252.1_avgqu.sz',
#  'dev252.1_.util',
#  'cpu7_.idle',
#  'all_..iowait',
#  'dev252.1_await',
#  'eth0_rxkB.s',
#  'dev8.0_svctm',
#  'cpu9_.usr',
#  'eth0_txkB.s',
#  'cpu1_.iowait',
#  'cpu6_.iowait',
#  'frmpg.s',
#  'cpu11_.usr',
#  'cpu7_.usr',
#  'cpu5_.idle',
#  'cpu1_.idle',
#  'X..commit',
#  'X..memused',
#  'X..swpused',
#  'cpu3_.idle',
#  'cpu23_.idle',
#  'X..swpcad',
#  'cpu13_.idle',
#  'cpu17_.idle',
#  'cpu21_.idle',
#  'cpu15_.idle',
#  'cpu19_.idle',
#  'cpu22_.idle',
#  'cpu18_.idle',
#  'cpu2_.idle',
#  'cpu4_.idle',
#  'cpu20_.idle',
#  'cpu14_.idle',
#  'cpu0_.idle',
#  'cpu10_.idle',
#  'cpu16_.idle',
#  'cpu6_.idle',
#  'all_..idle',
#  'cpu8_.idle',
#  'cpu12_.idle']